### PR TITLE
[WIP] fix(osio): Fixes #64: Develop /osio/launch

### LINKED ISSUE #64: Develop /osio/launch
Parent #47

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by gastaldi** [comment]
Retest this please

**Comment by gastaldi** [comment]
retest this please

File: addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java [hunk 1]
```diff
@@ -1,25 +1,91 @@
...
+            gitService.push(repository, projectLocation);
+        }
+        statusEvent.fire(new StatusMessageEvent(projectile.getId(), GITHUB_PUSHED));
+    }
+
+    /**
+     * Creates a webhook on the github repo to fire a build / deploy when changes happen on the project.
+     */
+    public void createWebHooks(OsioProjectile projectile, GitRepository gitRepository) {
+        String jenkinsWebhookURL = EnvironmentVariables.ExternalServices.getJenkinsWebhookURL();
```
Comment (edewit) [inline addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java]: Don't think you can do this as there are multiple jenkins servers, depending on the user this url can be different

File: addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/Tenant.java [hunk 2]
```diff
@@ -14,10 +15,24 @@
...
+    TokenIdentity getIdentity();
+
     List<Namespace> getNamespaces();
 
+    @Value.Derived
+    default Namespace getDefaultUserNamespace() {
+        return getNamespaces().stream()
+                .filter(Namespace::isUserNamespace)
+                .findFirst()
+                .orElseThrow(() -> new IllegalStateException("No user namespace found for " + getUsername()));
```
Comment (edewit) [inline addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/Tenant.java]: In the original code a null could be returned, don't know if that is really possible, but we might want to keep it the same?

File: addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java (hunk 1 above)
Comment (gastaldi) [reply addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/GitSteps.java]: Nope, this changed in the last couple of months 😁. Now Jenkins is a fixed URL. See https://github.com/fabric8-launcher/launcher-backend/commit/c897fae072566c729ff25cc25adde561b0690e2b

File: addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/Tenant.java (hunk 2 above)
Comment (gastaldi) [reply addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/tenant/Tenant.java]: Afaik in the original code an exception was thrown if no namespace was found, so let's never assume this method will return null

File: addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java [hunk 3]
```diff
@@ -2,39 +2,74 @@
...
+    private Tenant tenant;
+
+
     public void createBuildConfig(OsioProjectile projectile) {
         Map<String, String> annotations = getBuildConfigAnnotations(projectile);
 
     }
 
+
+    public void triggerBuild(OsioProjectile projectile) {
```
Comment (edewit) [inline addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java]: wasn't the plan to create the webhooks first and then push the code so that we don't have to trigger a build manually but let the webhook take care of that?

Comment (gastaldi) [reply addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java]: Yes, that method was just a first step in the refactoring process, feel free to remove it as you like

File: addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java [hunk 4]
```diff
@@ -43,4 +105,34 @@ public void createBuildConfig(OsioProjectile projectile) {
         annotations.put(Annotations.JENKINS_DISABLE_SYNC_CREATE_ON, "jenkins");
         return annotations;
     }
+
+    private String getSpaceIdFromSpacePath(String spacePath) {
+        return spacePath.substring(1);
```
Comment (gastaldi) [inline addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java]: Why is this method doing a substring?

Comment (edewit) [reply addons/new-osio-addon/src/main/java/io/fabric8/launcher/osio/steps/OpenShiftSteps.java]: because spacePath looks like "/my-space" and we need only the my-space part

**Comment by gastaldi** [comment]
Shouldn't we at least check the input before doing that?

On Feb 20, 2018 12:34 PM, "Erik Jan de Wit" <notifications@github.com>
wrote:

*@edewit* commented on this pull request.
------------------------------

In addons/new-osio-addon/src/main/java/io/fabric8/launcher/
osio/steps/OpenShiftSteps.java
<https://github.com/fabric8-launcher/launcher-backend/pull/70#discussion_r169304098>
:

> @@ -43,4 +105,34 @@ public void createBuildConfig(OsioProjectile projectile) {
         annotations.put(Annotations.JENKINS_DISABLE_SYNC_CREATE_ON, "jenkins");
         return annotations;
     }
+
+    private String getSpaceIdFromSpacePath(String spacePath) {
+        return spacePath.substring(1);

because spacePath looks like "/my-space" and we need only the my-space part

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fabric8-launcher/launcher-backend/pull/70#discussion_r169304098>,
or mute the thread

**Comment by edewit** [comment]
isn't that what the validate is for?

**Comment by gastaldi** [comment]
I don't see a @Pattern in the spacePath in OsioProjectileContext impl requiring it to have a `/` as the first char :)
